theme: jekyll-theme-midnight
title: "Práctica 11: Cliente y servidor para una aplicación de procesamiento de notas de texto"
description: "Partiendo de la aplicación de procesamiento de notas, escribir un servidor y un cliente haciendo uso de sockets para su funcionalidad."
